In [7]:
import mysql.connector
from sqlalchemy import create_engine
import pandas as pd

# Replace 'your_username', 'your_password', 'your_database', and 'your_host' with actual values
db_connection = mysql.connector.connect(
    user='root',
    password='12345',
    host='localhost',
    database='bat_algo_database'
)

# Path to your CSV file
csv_file_path = r'C:\Users\user\BAT_ALGORITHM_FULL\processed_data_bat_full.csv'

# Read CSV file into a pandas DataFrame
df = pd.read_csv(csv_file_path)

# Define the table name (avoid spaces)
table_name = 'data_collected'

# Create SQLAlchemy engine
engine = create_engine('mysql+mysqlconnector://root:12345@localhost/bat_algo_database')

try:
    # Create MySQL table based on DataFrame structure
    df[:0].to_sql(table_name, con=engine, index=False, if_exists='replace')

    # Load data into MySQL table
    df.to_sql(table_name, con=engine, index=False, if_exists='append')

    print(f'Data has been successfully loaded into the {table_name} table.')

except Exception as e:
    print(f'Error: {str(e)}')

finally:
    # Close the database connection
    db_connection.close()

Data has been successfully loaded into the data_collected table.

In [9]:
table_name = 'data_collected'

# Create SQLAlchemy engine
engine = create_engine('mysql+mysqlconnector://root:12345@localhost/bat_algo_database')

# Query data from MySQL table into a DataFrame
query = f"SELECT * FROM {table_name}"
df = pd.read_sql(query, con=engine)

# Define the path to save the CSV file
csv_file_path = r'C:\Users\user\BAT_ALGORITHM_FULL\exported_data.csv'

# Write the DataFrame to CSV
df.to_csv(csv_file_path, index=False)

print(f'Data from the {table_name} table has been successfully exported to {csv_file_path}.')

Data from the data_collected table has been successfully exported to C:\Users\user\BAT_ALGORITHM_FULL\exported_data.csv.

In [10]:
cursor.close()
db_connection.close()

In [12]:
df

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,outcome,level
0,0,tcp,private,REJ,0,0,0,0,0,0,...,0.00,0.06,0.00,0.00,0.00,0.0,1.00,1.00,neptune,21
1,2,tcp,ftp_data,SF,12983,0,0,0,0,0,...,0.61,0.04,0.61,0.02,0.00,0.0,0.00,0.00,normal,21
2,0,icmp,eco_i,SF,20,0,0,0,0,0,...,1.00,0.00,1.00,0.28,0.00,0.0,0.00,0.00,saint,15
3,1,tcp,telnet,RSTO,0,15,0,0,0,0,...,0.31,0.17,0.03,0.02,0.00,0.0,0.83,0.71,mscan,11
4,0,tcp,http,SF,267,14515,0,0,0,0,...,1.00,0.00,0.01,0.03,0.01,0.0,0.00,0.00,normal,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22538,0,tcp,smtp,SF,794,333,0,0,0,0,...,0.72,0.06,0.01,0.01,0.01,0.0,0.00,0.00,normal,21
22539,0,tcp,http,SF,317,938,0,0,0,0,...,1.00,0.00,0.01,0.01,0.01,0.0,0.00,0.00,normal,21
22540,0,tcp,http,SF,54540,8314,0,0,0,2,...,1.00,0.00,0.00,0.00,0.00,0.0,0.07,0.07,back,15
22541,0,udp,domain_u,SF,42,42,0,0,0,0,...,0.99,0.01,0.00,0.00,0.00,0.0,0.00,0.00,normal,21
22542,0,tcp,sunrpc,REJ,0,0,0,0,0,0,...,0.08,0.03,0.00,0.00,0.00,0.0,0.44,1.00,mscan,14

In [14]:
data_train=pd.read_csv(r'C:\Users\user\BAT_ALGORITHM_FULL\exported_data.csv')

In [15]:
import numpy as np
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras import regularizers
import xgboost as xgb
from sklearn.decomposition import PCA
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import RobustScaler
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
pd.set_option('display.max_columns',None)
warnings.filterwarnings('ignore')
%matplotlib inline

ModuleNotFoundError: No module named 'tensorflow'